### PR TITLE
docs: show how to iterate over intervals in order

### PR DESCRIPTION
**Pull request by sietse**
Move information from issue #44 into README

### CODE REVIEW

**Comment by sietse** [comment]
Hullo Alexandre,
Thank you for Portion, it is very useful, especially its IntervalDict.

How would you feel about explaining 'iterate over atomic intervals in order' in the main README, rather than linking to a issue? If you like that idea, this pull request implements that. Do feel free to adjust it to your liking.

Motivation: so far, every time I used an IntervalDict it represented values over time; and I found myself needing to iterate over the intervals in temporal order. One time it was to run a simulation; another time it was to feed an external program that expected an ordered list of (start, stop, value); a third time I needed to generate the values for a plot. 3 different use cases seems common and varied enough that I propose moving this tip into the main README.

Open questions:
- Should I put this advice in the .items() docstring, too? At the REPL, the docstrings are more accessible than the README.
- Perhaps it's even worth creating a dedicated method for this -- `my_interval_dict.atomic_items()`? I'd be willing to work on that, too. But I figured I'd start small, and see how you feel about this docs change.

Kind regards,
Sietse

**Comment by AlexandreDecan** [comment]
Hello,

First of all, thank you for your interest in `portion`. I'm always happy to see this library being used, and potentially useful :-) 

Concerning the PR, I am rather divided. I understand the interest in mentioning the possibility to get atomic intervals from an `IntervalDict` but I think that the "documentation" (read: README, in the absence of a real documentation) should focus on the features that are directly offered by `portion` and not stray too much on the "features" that follow from it. 

In fact, this PR reminds me that there is still work to be done with `portion`, both in the code and, more importantly, in its documentation. I think the library would benefit from having a "real documentation" (and not just a README) in which these "advanced uses" could be concretely proposed and described. An alternative would be to offer these various "features" in the form of a `contrib` module with some of the usual routines (not only the example discussed in this PR, but also functions such as `.extend` or conversion to discrete intervals, etc. as mentioned in several issues so far). Another alternative would be to add a "Common recipes" section in the README to list these various examples. 

Going back to the topic of this PR, as it stands, I am rather in favour of *not* changing the README to include this example (in order to keep the README "simple") and to keep the pointer to the comment explaining how to achieve this result. This seems to me to balance the best of both worlds: the README doesn't get "bloated" while still providing the information that it is possible to get the (sorted list of) atomic intervals from an `IntervalDict`. 

Of the open questions you mention, the second point could possibly be implemented directly within the `.as_dict` function, e.g. in the form of an optional `atomic` parameter (`False` by default) which, if set to `True`, converts the dictionary keys into atomic ranges. If we go that direction, then obviously we will have to provide an example and to explain it in the README. What do you think about this?

**Comment by sietse** [comment]
Hello,

Just a brief reply for now, I'll try to write a longer reply sometime this week. Just wanted you to know that I've read your message and I haven't disappeared yet. 

- re: `IntervalDict.as_dict(atomic=True)` — the idea of allowing the user to choose 'atomic or not' when converting seems user-friendly, I think this is a good direction. (Default `False` for backwards-compatibility, as you say.) 

  I propose adding the same option to methods supporting iteration: `.items(atomic=True)` and `.keys(atomic=True)`. Their docstrings already promise "Return a view object on the contained items _sorted by key_" (emphasis mine), so by adding the 'atomic' option we immediately cover the atomic+sorted usecase. The resulting code is nice:

      timeline = P.IntervalDict()
      # ... fill it with data ....
      for interval, value in timeline.items(atomic=True):
          ...

  If we only `.as_dict(atomic=True)` is useful for users who want a collection. But because Python dicts are FIFO-ordered but not sorted, sorted iteration on dicts is noisier than with IntervalDict above:

      timeline = P.IntervalDict()
      # ... fill it with data ....
      for interval, value in sorted(timeline.as_dict(atomic=True).items()):
          ...

  So IntervalDict `.as_dict(atomic=True)`, `.items(atomic=True)`, and `.values(atomic=True)` looks like it's small in scope and covers a lot of usecases, what do you think? 

- Regarding docs: don't sell yourself short! The docs may be all in the README, but that's just a place -- contentwise, the documentation is excellent, very complete. I'd say it is very 'real' indeed :D 

Cheers,
Sietse

**Comment by AlexandreDecan** [comment]
I'm closing this PR since we're moving towards a change in the code (and in the documentation) rather than a "simple" adaptation of the documentation. I propose to create a new issue so we can discuss the best way to address the underlying problem :-) 

Thank you!

**Comment by sietse** [comment]
Ha, crossed messages! You're right, this is more of a code discussion now.

I'll wait for you to open the issue, and if my previous message is still relevant I'll copy the relevant bits over. No need to open an issue now-now, by the way, just whenever your schedule suits you.

**Comment by AlexandreDecan** [comment]
:+1:

**Pull request closed without merging**
