### PR TITLE
Fix printing of Interval object within Pandas.DataFrame

### PR DESCRIPTION
**Pull request by alexprincel**
This fixes issue brought up here https://github.com/pandas-dev/pandas/issues/40081

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Thanks for the PR, and the explanations and pointers you provided in  pandas-dev/pandas#40081. 

I do not really like the idea of "neutralizing" `__next__` just because of a display issue in `pandas`, esp. since neutralizing it means it will be recognized by `hasattr`. While I understand this is "on purpose" for the issue being discussed, it could have many side effects since `__next__` is usually the way to identify support of the iterator protocol (and we do not support this protocol).

I'll wait a little bit before deciding on this PR. I would like first to see if I can find another solution, either in `portion` or perhaps even in `pandas`, since I think the "issue" is more on their side by bypassing the `__repr__` protocol.

**Comment by AlexandreDecan** [comment]
I cannot find any other reasonable solution for this issue. An `Interval` is an iterable, not an iterator, and a such, I'm a bit reluctant to define a "dummy" `__next__` method on it. I'm afraid of any potential side effect the presence of this method could have in practice. At the same time, I expect `portion` to be used in combination with `pandas` and the current way intervals are displayed is not only confusing but also misleading (since only the first atomic interval in a conjunction of atomic intervals will be actually displayed by `pandas`, therefore not even correctly representing the actual content of the conjunction).

**Comment by AlexandreDecan** [comment]
Inspired by your solution based on the presence of `__next__`, and not satisfied by the potential side effects it could have, I made the following ugly-but-safe hack in `Interval`:

```python
    def __getattr__(self, name):
        if name == '__next__':
            # Hack for a better representation of intervals within pandas
            # See https://github.com/AlexandreDecan/portion/pull/54
            try:
                import inspect
                if inspect.stack()[1].function == 'pprint_thing':
                    return
            except Exception:
                pass
        raise AttributeError
```

It's ugly, for sure, but it's safe since we make sure it only (mostly) applies when call from `pandas`, does not affect any other call. Obviously, `inspect` is not safe to use in all implementations of Python (hence the `try... except`) but in that case, the current behaviour will apply. 

What do you think? :)

**Comment by alexprincel** [comment]
While hacky, I think you're right that this method is safer in other contexts where __next__ is used for duck typing.

**Comment by AlexandreDecan** [comment]
I'll go that way then ;-)

Thank you!!

**Pull request closed without merging**
